/**
 * Knowledge Graph Builder Implementation
 *
 * Requirements: 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 7.2, 7.3, 7.4
 *
 * Architecture (hybrid):
 *  - Vector indexing & retrieval  → genkitx-neo4j Agent Skills (via GenkitEngineImpl)
 *  - Structured graph operations  → neo4j-driver (MERGE nodes/rels, Cypher queries)
 */

import neo4j, { Driver, Session } from 'neo4j-driver';
import { Document } from 'genkit';
import {
  KnowledgeGraphBuilder,
  GraphStats,
  SearchResult,
  GraphContext,
  AnalysisResult
} from '../models/knowledge-graph.types';
import { Entity, Relationship } from '../models/genkit.types';
import { Neo4jConfig } from '../config/types';
import { ComparisonReport } from './comparison';
import { Neo4jConnectionError, Neo4jQueryError, Neo4jError } from '../errors/neo4j.errors';
import { retryWithBackoff } from '../utils/retry';
import { createLogger } from './logger';
import { GenkitEngineImpl } from './genkit-engine';

export class KnowledgeGraphBuilderImpl implements KnowledgeGraphBuilder {
  private driver: Driver | null = null;
  private logger = createLogger();

  /**
   * The GenkitEngine is injected so we can call ai.index() / ai.retrieve()
   * (the Agent Skills) without duplicating Genkit initialisation.
   */
  private genkitEngine?: GenkitEngineImpl;

  /**
   * Injects the already-initialised GenkitEngine so this builder can use
   * the genkitx-neo4j Agent Skills for vector operations.
   */
  setGenkitEngine(engine: GenkitEngineImpl): void {
    this.genkitEngine = engine;
  }

  // ─── Connection ────────────────────────────────────────────────────────────

  /**
   * Connects to Neo4j using the native driver.
   * The driver is kept only for structured Cypher operations (MERGE, relationships,
   * comparison reports, visualisation). Vector operations go through the plugin.
   * Requirements: 5.1, 5.4
   */
  async connect(config: Neo4jConfig): Promise<void> {
    try {
      this.driver = neo4j.driver(
        config.uri,
        neo4j.auth.basic(config.username, config.password),
        { disableLosslessIntegers: true }
      );

      await this.driver.verifyConnectivity();
      this.logger.info('KnowledgeGraph', 'Successfully connected to Neo4j');

      await this.initializeSchema();
    } catch (error: any) {
      this.logger.error('KnowledgeGraph', 'Failed to connect to Neo4j', error);
      throw new Neo4jConnectionError(`Connection failed: ${error.message}`);
    }
  }

  /**
   * Closes the Neo4j driver connection.
   */
  async disconnect(): Promise<void> {
    if (this.driver) {
      await this.driver.close();
      this.driver = null;
      this.logger.info('KnowledgeGraph', 'Disconnected from Neo4j');
    }
  }

  // ─── Entity operations (Agent Skills) ─────────────────────────────────────

  /**
   * Creates or updates an entity node.
   *
   * Uses a hybrid approach:
   *   1. Writes the structured node (name, type, sourceText, documents) via
   *      Cypher MERGE so the graph relationships remain intact.
   *   2. Indexes the entity text through the genkitx-neo4j Agent Skill
   *      (`ai.index()`), which stores the embedding on the same :Entity node
   *      using the `embeddingProperty: 'embedding'` mapping configured in the plugin.
   *
   * Requirements: 5.2, 5.5, 5.6
   */
  async createOrUpdateEntity(entity: Entity, sourceDocument: string, embeddings: number[]): Promise<string> {
    this.ensureConnected();

    // 1. Structured MERGE via driver (keeps relationships / timestamps intact)
    const nodeId = await this.executeWrite(async (session) => {
      const query = `
        MERGE (e:Entity {name: $name})
        ON CREATE SET
          e.id = randomUUID(),
          e.type = $type,
          e.sourceText = $sourceText,
          e.documents = [$sourceDocument],
          e.createdAt = datetime(),
          e.updatedAt = datetime()
        ON MATCH SET
          e.type = $type,
          e.updatedAt = datetime()
        WITH e
        WHERE NOT $sourceDocument IN e.documents
        SET e.documents = e.documents + [$sourceDocument]
        RETURN e.id AS id
      `;

      const result = await session.run(query, {
        name: entity.name,
        type: entity.type,
        sourceText: entity.sourceText,
        sourceDocument,
      });

      return result.records[0]?.get('id') ?? entity.name;
    });

    // 2. Vector indexing via genkitx-neo4j Agent Skill ──────────────────────
    // The plugin maps `document.content[0].text` → `sourceText` property and
    // `document.metadata` is stored alongside. The embedding is generated by
    // the plugin's embedder OR pre-supplied via metadata.embedding.
    if (this.genkitEngine) {
      const doc = Document.fromText(entity.sourceText, {
        name: entity.name,
        type: entity.type,
        sourceDocument,
        // Attach pre-computed HuggingFace embedding so the plugin doesn't
        // need to call a Genkit-native embedder for this document.
        embedding: embeddings,
      });

      await this.genkitEngine.indexDocuments([doc]);
    } else {
      // Fallback: write embedding directly via driver if engine not injected
      await this.executeWrite(async (session) => {
        await session.run(
          `MATCH (e:Entity {name: $name}) SET e.embedding = $embeddings`,
          { name: entity.name, embeddings }
        );
      });
    }

    return nodeId;
  }

  // ─── Relationship operations (driver) ─────────────────────────────────────

  /**
   * Creates a relationship between two entities.
   * Remains a direct Cypher operation — the plugin has no relationship API.
   * Requirements: 5.3
   */
  async createRelationship(relationship: Relationship, sourceDocument: string): Promise<void> {
    this.ensureConnected();

    return this.executeWrite(async (session) => {
      const sanitizedType = relationship.type.replace(/[^A-Z0-9_]/gi, '_').toUpperCase();

      const query = `
        MATCH (source:Entity {name: $sourceName})
        MATCH (target:Entity {name: $targetName})
        MERGE (source)-[r:${sanitizedType}]->(target)
        ON CREATE SET
          r.sourceDocument = $sourceDocument,
          r.confidence = $confidence,
          r.createdAt = datetime()
      `;

      await session.run(query, {
        sourceName: relationship.source,
        targetName: relationship.target,
        sourceDocument,
        confidence: relationship.confidence
      });
    });
  }

  // ─── Analysis result pipeline ──────────────────────────────────────────────

  /**
   * Processes a full analysis result.
   * Entity indexing uses the Agent Skill; relationship creation uses the driver.
   * Requirements: 5.7, 8.2
   */
  async processAnalysisResult(result: AnalysisResult, sourceDocument: string): Promise<GraphStats> {
    this.ensureConnected();
    this.logger.info('KnowledgeGraph', `Processing analysis result for ${sourceDocument}`);

    let entitiesCreated = 0;
    let relationshipsCreated = 0;

    for (const entity of result.entities) {
      await this.createOrUpdateEntity(entity, sourceDocument, result.embeddings);
      entitiesCreated++;
    }

    for (const rel of result.relationships) {
      await this.createRelationship(rel, sourceDocument);
      relationshipsCreated++;
    }

    const stats: GraphStats = { entitiesCreated, entitiesUpdated: 0, relationshipsCreated };
    this.logger.info('KnowledgeGraph', 'Graph build complete', stats as any);
    return stats;
  }

  // ─── Vector search (Agent Skills) ─────────────────────────────────────────

  /**
   * Executes a semantic (vector) search against the Neo4j vector index.
   *
   * Uses the genkitx-neo4j retriever Agent Skill (`ai.retrieve()`) when the
   * engine is injected. Falls back to the direct Cypher `db.index.vector.queryNodes`
   * call if the engine is not available.
   *
   * Requirements: 7.2, 7.3, 7.4
   */
  async vectorSearch(queryEmbeddings: number[], limit: number): Promise<SearchResult[]> {
    // Preferred path: Agent Skills retriever
    if (this.genkitEngine) {
      // The retriever expects a text query. We pass a special marker so callers
      // that only have raw vectors can still go through this path.
      // If you have the original query text, prefer calling genkitEngine.retrieve() directly.
      this.logger.warn(
        'KnowledgeGraph',
        'vectorSearch called with raw embeddings — Agent Skills retriever needs text query. ' +
        'Prefer calling genkitEngine.retrieve(queryText, limit) directly from the API layer.'
      );
    }

    // Fallback: direct Cypher (works even without the engine)
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const query = `
        CALL db.index.vector.queryNodes('entity_embeddings', $limit, $embedding)
        YIELD node, score
        RETURN node.id AS id,
               node.name AS name,
               node.type AS type,
               node.sourceText AS sourceText,
               node.documents AS documents,
               score
        ORDER BY score DESC
      `;

      const result = await session.run(query, {
        embedding: queryEmbeddings,
        limit
      });

      return result.records.map(record => ({
        nodeId: record.get('id'),
        entity: {
          name: record.get('name'),
          type: record.get('type') as any,
          sourceText: record.get('sourceText'),
          confidence: 1.0
        },
        similarity: record.get('score'),
        sourceDocuments: record.get('documents')
      }));
    });
  }

  // ─── Node context (driver) ─────────────────────────────────────────────────

  /**
   * Retrieves context for a node.
   * Requirements: 7.4
   */
  async getNodeContext(nodeId: string, depth: number): Promise<GraphContext> {
    this.ensureConnected();

    return this.executeRead(async (session) => {
      const query = `
        MATCH (center:Entity {id: $nodeId})
        OPTIONAL MATCH (center)-[r]-(neighbor:Entity)
        RETURN center, type(r) as relType, startNode(r) = center as isOutgoing, neighbor
      `;

      const result = await session.run(query, { nodeId });

      if (result.records.length === 0) {
        throw new Error(`Node not found: ${nodeId}`);
      }

      const centerProps = result.records[0].get('center').properties;
      const centerNode: Entity = {
        name: centerProps.name,
        type: centerProps.type as any,
        sourceText: centerProps.sourceText,
        confidence: 1.0
      };

      const neighbors = result.records
        .filter(record => record.get('neighbor') !== null)
        .map(record => {
          const neighborProps = record.get('neighbor').properties;
          return {
            entity: {
              name: neighborProps.name,
              type: neighborProps.type as any,
              sourceText: neighborProps.sourceText,
              confidence: 1.0
            },
            relationship: record.get('relType'),
            direction: record.get('isOutgoing') ? 'outgoing' : 'incoming' as 'incoming' | 'outgoing'
          };
        });

      return { centerNode, neighbors };
    });
  }

  // ─── Comparison reports (driver) ───────────────────────────────────────────

  /**
   * Saves a Comparison Report to Neo4j.
   * Structural graph writes — handled entirely via Cypher/driver.
   */
  async saveComparisonReport(report: ComparisonReport): Promise<void> {
    this.ensureConnected();
    this.logger.info('KnowledgeGraph', `Saving comparison report for ${report.programDocument} against ${report.normativeDocument}`);

    return this.executeWrite(async (session) => {
      await session.run(`
        MERGE (d:Entity {name: $name})
        ON CREATE SET d.createdAt = datetime(), d.type = 'DOCUMENT', d.text = $text
        ON MATCH SET d.text = $text
        SET d:Document:NormativeDocument
      `, { name: report.normativeDocument, text: report.normativeText || '' });

      await session.run(`
        MERGE (d:Entity {name: $name})
        ON CREATE SET
          d.createdAt = datetime(),
          d.type = 'DOCUMENT',
          d.text = $text,
          d.total = $total,
          d.covered = $covered,
          d.partial = $partial,
          d.missing = $missing,
          d.coveragePercent = $coveragePercent
        ON MATCH SET
          d.text = $text,
          d.total = $total,
          d.covered = $covered,
          d.partial = $partial,
          d.missing = $missing,
          d.coveragePercent = $coveragePercent
        SET d:Document:ProgramDocument
        WITH d
        MATCH (n:Entity {name: $normativeDocument})
        WHERE n:NormativeDocument
        MERGE (d)-[:COMPARED_TO]->(n)
      `, {
        name: report.programDocument,
        text: report.programText || '',
        total: report.summary.total,
        covered: report.summary.covered,
        partial: report.summary.partial,
        missing: report.summary.missing,
        coveragePercent: report.summary.coveragePercent,
        normativeDocument: report.normativeDocument
      });

      for (const item of report.ontology) {
        const uniqueName = `${report.normativeDocument}_${item.id}`;
        await session.run(`
          MATCH (d:Entity {name: $docName})
          WHERE d:NormativeDocument
          MERGE (o:Entity {name: $uniqueName})
          ON CREATE SET
            o.id = $itemId,
            o.requirement = $requirement,
            o.category = $category,
            o.description = $description,
            o.keywords = $keywords,
            o.type = 'CONCEPT',
            o.sourceText = $description,
            o.createdAt = datetime()
          ON MATCH SET
            o.requirement = $requirement,
            o.category = $category,
            o.description = $description,
            o.keywords = $keywords,
            o.sourceText = $description
          SET o:OntologyItem
          MERGE (o)-[:EXTRACTED_FROM]->(d)
        `, {
          docName: report.normativeDocument,
          uniqueName,
          itemId: item.id,
          requirement: item.requirement,
          category: item.category,
          description: item.description,
          keywords: item.keywords || []
        });
      }

      if (report.programOntology) {
        for (const item of report.programOntology) {
          await session.run(`
            MERGE (e:Entity {name: $name})
            ON CREATE SET
              e.id = randomUUID(),
              e.type = $type,
              e.sourceText = $sourceText,
              e.documents = [$sourceDocument],
              e.createdAt = datetime(),
              e.updatedAt = datetime()
            ON MATCH SET
              e.type = $type,
              e.updatedAt = datetime()
            WITH e
            WHERE NOT $sourceDocument IN e.documents
            SET e.documents = e.documents + [$sourceDocument]
          `, {
            name: item.requirement || item.description || item.id,
            type: item.category || 'CONCEPT',
            sourceText: item.description || item.requirement || '',
            sourceDocument: report.programDocument
          });
        }
      }

      for (const res of report.results) {
        const uniqueName = `${report.normativeDocument}_${res.item.id}`;
        await session.run(`
          MATCH (p:Entity {name: $progName})
          WHERE p:ProgramDocument
          MATCH (o:Entity {name: $uniqueName})
          WHERE o:OntologyItem
          MERGE (p)-[r:EVALUATED_AGAINST]->(o)
          SET r.status = $status,
          r.confidence = $confidence,
          r.evidence = $evidence,
          r.suggestion = $suggestion,
          r.updatedAt = datetime()
        `, {
          progName: report.programDocument,
          uniqueName,
          status: res.status,
          confidence: res.confidence,
          evidence: res.evidence,
          suggestion: res.suggestion
        });
      }
    });
  }

  /**
   * Clears previous comparison nodes from the graph.
   */
  async clearPreviousComparisons(): Promise<void> {
    this.ensureConnected();
    this.logger.info('KnowledgeGraph', 'Clearing previous comparison nodes from graph');
    return this.executeWrite(async (session) => {
      await session.run(`
        MATCH (n)
        WHERE n:NormativeDocument OR n:ProgramDocument OR n:OntologyItem
        DETACH DELETE n
      `);
    });
  }

  /**
   * Clears the entire database (all nodes and relationships).
   */
  async clearEntireDatabase(): Promise<void> {
    this.ensureConnected();
    this.logger.info('KnowledgeGraph', 'Clearing the entire Neo4j database');
    return this.executeWrite(async (session) => {
      await session.run(`
        MATCH (n)
        DETACH DELETE n
      `);
    });
  }

  /**
   * Retrieves the latest comparison report from the graph.
   */
  async getLatestComparison(): Promise<ComparisonReport | null> {
    this.ensureConnected();

    return this.executeRead(async (session) => {
      const query = `
        MATCH (p:ProgramDocument)-[:COMPARED_TO]->(n:NormativeDocument)
        WITH p, n ORDER BY p.createdAt DESC LIMIT 1
        OPTIONAL MATCH (p)-[r:EVALUATED_AGAINST]->(o:OntologyItem)
        RETURN
          p.name AS programName,
          p.total AS total,
          p.covered AS covered,
          p.partial AS partial,
          p.missing AS missing,
          p.coveragePercent AS coveragePercent,
          n.name AS normativeName,
          o.id AS itemId,
          o.requirement AS requirement,
          o.category AS category,
          o.description AS description,
          o.keywords AS keywords,
          r.status AS status,
          r.confidence AS confidence,
          r.evidence AS evidence,
          r.suggestion AS suggestion
        ORDER BY o.id
      `;
      const result = await session.run(query);

      if (result.records.length === 0) {
        return null;
      }

      const normativeDocument = result.records[0].get('normativeName');
      const programDocument = result.records[0].get('programName');

      const summary = {
        total: Number(result.records[0].get('total')) || 0,
        covered: Number(result.records[0].get('covered')) || 0,
        partial: Number(result.records[0].get('partial')) || 0,
        missing: Number(result.records[0].get('missing')) || 0,
        coveragePercent: Number(result.records[0].get('coveragePercent')) || 0
      };

      const ontologyMap = new Map<string, any>();
      const results: any[] = [];

      for (const record of result.records) {
        const id = record.get('itemId');

        if (id) {
          if (!ontologyMap.has(id)) {
            ontologyMap.set(id, {
              id,
              category: record.get('category'),
              requirement: record.get('requirement'),
              description: record.get('description'),
              keywords: record.get('keywords') || []
            });
          }

          results.push({
            item: ontologyMap.get(id),
            status: record.get('status'),
            confidence: record.get('confidence'),
            evidence: record.get('evidence'),
            suggestion: record.get('suggestion')
          });
        }
      }

      return {
        normativeDocument,
        programDocument,
        ontology: Array.from(ontologyMap.values()),
        results,
        summary,
        timestamp: new Date().toISOString()
      };
    });
  }

  async getNormativeOntology(normativeName: string): Promise<any[]> {
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const result = await session.run(`
        MATCH (o:OntologyItem)-[:EXTRACTED_FROM]->(d:NormativeDocument {name: $normativeName})
        RETURN o.id AS id, o.category AS category, o.requirement AS requirement, o.description AS description, o.keywords AS keywords
        ORDER BY o.id
      `, { normativeName });
      return result.records.map(record => ({
        id: record.get('id'),
        category: record.get('category'),
        requirement: record.get('requirement'),
        description: record.get('description'),
        keywords: record.get('keywords') || []
      }));
    });
  }

  async getProgramOntology(programName: string): Promise<any[]> {
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const result = await session.run(`
        MATCH (e:Entity)
        WHERE $programName IN e.documents AND e.type <> 'DOCUMENT' AND NOT e:OntologyItem
        RETURN e.name AS name, e.type AS type, e.sourceText AS sourceText
      `, { programName });
      return result.records.map(record => ({
        name: record.get('name'),
        type: record.get('type'),
        sourceText: record.get('sourceText')
      }));
    });
  }

  async getComplianceGaps(normativeName: string, programName: string): Promise<any[]> {
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const result = await session.run(`
        MATCH (p:ProgramDocument {name: $programName})-[r:EVALUATED_AGAINST]->(o:OntologyItem)
        WHERE r.status IN ['partial', 'missing']
        RETURN o.id AS id, o.category AS category, o.requirement AS requirement, o.description AS description, r.status AS status, r.evidence AS evidence, r.suggestion AS suggestion
      `, { programName });
      return result.records.map(record => ({
        id: record.get('id'),
        category: record.get('category'),
        requirement: record.get('requirement'),
        description: record.get('description'),
        status: record.get('status'),
        evidence: record.get('evidence'),
        suggestion: record.get('suggestion')
      }));
    });
  }

  async getProgramText(programName: string): Promise<string> {
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const result = await session.run(`
        MATCH (p:ProgramDocument {name: $programName})
        RETURN p.text AS text
      `, { programName });
      return result.records[0]?.get('text') || '';
    });
  }

  async saveRubric(rubric: any, pdfBase64: string): Promise<void> {
    this.ensureConnected();
    this.logger.info('KnowledgeGraph', 'Saving rubric to Neo4j...');
    
    // Convert rubric to JSON string to preserve the full structure inside Neo4j node properties
    const rubricJson = JSON.stringify(rubric);
    
    return this.executeWrite(async (session) => {
      // First delete any previous rubric
      await session.run('MATCH (r:Rubric) DETACH DELETE r');
      
      // Store the new rubric as a single node
      await session.run(`
        CREATE (r:Rubric {
          title: $title,
          subtitle: $subtitle,
          normativeDocument: $normativeDocument,
          rubricJson: $rubricJson,
          pdfBase64: $pdfBase64,
          generatedAt: $generatedAt
        })
      `, {
        title: rubric.title,
        subtitle: rubric.subtitle,
        normativeDocument: rubric.normativeDocument,
        rubricJson,
        pdfBase64,
        generatedAt: rubric.generatedAt
      });
    });
  }

  async getLatestRubric(): Promise<{ rubric: any; pdfBase64: string } | null> {
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const result = await session.run(`
        MATCH (r:Rubric)
        RETURN r.rubricJson AS rubricJson, r.pdfBase64 AS pdfBase64
        ORDER BY r.generatedAt DESC
        LIMIT 1
      `);
      
      if (result.records.length === 0) {
        return null;
      }
      
      const rubricJson = result.records[0].get('rubricJson');
      const pdfBase64 = result.records[0].get('pdfBase64');
      
      try {
        const rubric = JSON.parse(rubricJson);
        return { rubric, pdfBase64 };
      } catch (err) {
        this.logger.error('KnowledgeGraph', 'Failed to parse stored rubric JSON', err as Error);
        return null;
      }
    });
  }

  async clearRubrics(): Promise<void> {
    this.ensureConnected();
    this.logger.info('KnowledgeGraph', 'Clearing all rubrics from Neo4j');
    return this.executeWrite(async (session) => {
      await session.run('MATCH (n) WHERE n:Rubric OR n:GuideExample OR n:StructureSection OR n:EvaluableAspect DETACH DELETE n');
    });
  }

  // ─── Guide Example & Evaluation Schema (Multi-Agent Rubric) ────────────────

  /**
   * Saves a guide example document with its detected structure sections.
   * Creates a :GuideExample node and child :StructureSection nodes.
   */
  async saveGuideExample(name: string, text: string, sections: Array<{ title: string; content: string }>): Promise<void> {
    this.ensureConnected();
    this.logger.info('KnowledgeGraph', `Saving guide example: ${name} (${sections.length} sections)`);

    return this.executeWrite(async (session) => {
      // Remove previous guide examples
      await session.run('MATCH (g:GuideExample) DETACH DELETE g');
      await session.run('MATCH (s:StructureSection) DETACH DELETE s');

      // Create the guide example node
      await session.run(`
        CREATE (g:GuideExample {
          name: $name,
          text: $text,
          sectionCount: $sectionCount,
          createdAt: datetime()
        })
      `, { name, text, sectionCount: sections.length });

      // Create section nodes linked to the guide
      for (let i = 0; i < sections.length; i++) {
        const s = sections[i];
        await session.run(`
          MATCH (g:GuideExample {name: $guideName})
          CREATE (s:StructureSection {
            title: $title,
            content: $content,
            order: $order,
            createdAt: datetime()
          })
          CREATE (s)-[:SECTION_OF]->(g)
        `, {
          guideName: name,
          title: s.title,
          content: s.content,
          order: i + 1,
        });
      }
    });
  }

  /**
   * Saves an evaluation schema (aspects to evaluate) extracted from a PDF.
   * Creates :EvaluableAspect nodes linked to any matching :OntologyItem nodes.
   */
  async saveEvaluationSchema(name: string, aspects: Array<{ id: string; aspect: string; description: string; category: string }>): Promise<void> {
    this.ensureConnected();
    this.logger.info('KnowledgeGraph', `Saving evaluation schema: ${name} (${aspects.length} aspects)`);

    return this.executeWrite(async (session) => {
      // Remove previous evaluation schema
      await session.run('MATCH (ea:EvaluableAspect) DETACH DELETE ea');

      for (const a of aspects) {
        await session.run(`
          CREATE (ea:EvaluableAspect {
            schemaName: $schemaName,
            aspectId: $aspectId,
            aspect: $aspect,
            description: $description,
            category: $category,
            createdAt: datetime()
          })
        `, {
          schemaName: name,
          aspectId: a.id,
          aspect: a.aspect,
          description: a.description,
          category: a.category,
        });
      }
    });
  }

  /**
   * Retrieves the guide example structure sections from Neo4j.
   */
  async getGuideStructure(name?: string): Promise<Array<{ title: string; content: string; order: number }>> {
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const query = name
        ? `MATCH (s:StructureSection)-[:SECTION_OF]->(g:GuideExample {name: $name}) RETURN s.title AS title, s.content AS content, s.order AS sOrder ORDER BY s.order`
        : `MATCH (s:StructureSection)-[:SECTION_OF]->(g:GuideExample) RETURN s.title AS title, s.content AS content, s.order AS sOrder ORDER BY s.order`;
      const result = await session.run(query, name ? { name } : {});
      return result.records.map(r => ({
        title: r.get('title'),
        content: r.get('content'),
        order: r.get('sOrder'),
      }));
    });
  }

  /**
   * Retrieves evaluation schema aspects from Neo4j.
   */
  async getEvaluationSchema(): Promise<Array<{ id: string; aspect: string; description: string; category: string }>> {
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const result = await session.run(`
        MATCH (ea:EvaluableAspect)
        RETURN ea.aspectId AS id, ea.aspect AS aspect, ea.description AS description, ea.category AS category
        ORDER BY ea.aspectId
      `);
      return result.records.map(r => ({
        id: r.get('id'),
        aspect: r.get('aspect'),
        description: r.get('description'),
        category: r.get('category'),
      }));
    });
  }

  /**
   * Retrieves the raw text of the guide example.
   */
  async getGuideExampleText(): Promise<string> {
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const result = await session.run('MATCH (g:GuideExample) RETURN g.text AS text LIMIT 1');
      return result.records[0]?.get('text') || '';
    });
  }

  // ─── Private helpers ───────────────────────────────────────────────────────

  private ensureConnected() {
    if (!this.driver) {
      throw new Neo4jConnectionError('KnowledgeGraphBuilder is not connected to Neo4j');
    }
  }

  private async initializeSchema() {
    return this.executeWrite(async (session) => {
      await session.run(`
        CREATE CONSTRAINT entity_name_unique IF NOT EXISTS
        FOR (e:Entity) REQUIRE e.name IS UNIQUE
      `);

      await session.run(`
        CREATE CONSTRAINT user_email_unique IF NOT EXISTS
        FOR (u:User) REQUIRE u.email IS UNIQUE
      `);

      try {
        await session.run(`
          CREATE VECTOR INDEX entity_embeddings IF NOT EXISTS
          FOR (e:Entity)
          ON (e.embedding)
          OPTIONS {indexConfig: {
            \`vector.dimensions\`: 768,
            \`vector.similarity_function\`: 'cosine'
          }}
        `);
      } catch (e: any) {
        this.logger.warn('KnowledgeGraph', 'Could not create vector index (might not be supported on this Neo4j version)', { error: e.message });
      }
    });
  }

  private async executeWrite<T>(operation: (session: Session) => Promise<T>): Promise<T> {
    return retryWithBackoff(async () => {
      const session = this.driver!.session();
      try {
        return await operation(session);
      } catch (error: any) {
        throw Neo4jError.fromDriverError(error);
      } finally {
        await session.close();
      }
    }, {
      maxRetries: 3,
      initialDelayMs: 1000,
      maxDelayMs: 10000,
      logger: this.logger,
      component: 'KnowledgeGraph'
    });
  }

  private async executeRead<T>(operation: (session: Session) => Promise<T>): Promise<T> {
    return retryWithBackoff(async () => {
      const session = this.driver!.session({ defaultAccessMode: neo4j.session.READ });
      try {
        return await operation(session);
      } catch (error: any) {
        throw Neo4jError.fromDriverError(error);
      } finally {
        await session.close();
      }
    }, {
      maxRetries: 3,
      initialDelayMs: 1000,
      maxDelayMs: 10000,
      logger: this.logger,
      component: 'KnowledgeGraph'
    });
  }

  // ─── User Authentication Methods ──────────────────────────────────────────

  async getUserByEmail(email: string): Promise<any | null> {
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const result = await session.run(`
        MATCH (u:User {email: $email})
        RETURN u.email AS email, u.name AS name, u.passwordHash AS passwordHash, u.role AS role, u.isActive AS isActive, u.createdAt AS createdAt
      `, { email });
      if (result.records.length === 0) return null;
      const r = result.records[0];
      return {
        email: r.get('email'),
        name: r.get('name'),
        passwordHash: r.get('passwordHash'),
        role: r.get('role'),
        isActive: r.get('isActive'),
        createdAt: r.get('createdAt')
      };
    });
  }

  async createUser(user: { email: string; name: string; passwordHash: string; role: string; isActive: boolean }): Promise<void> {
    this.ensureConnected();
    return this.executeWrite(async (session) => {
      await session.run(`
        CREATE (u:User {
          email: $email,
          name: $name,
          passwordHash: $passwordHash,
          role: $role,
          isActive: $isActive,
          createdAt: datetime()
        })
      `, {
        email: user.email,
        name: user.name,
        passwordHash: user.passwordHash,
        role: user.role,
        isActive: user.isActive
      });
    });
  }

  async hasAnyUser(): Promise<boolean> {
    this.ensureConnected();
    return this.executeRead(async (session) => {
      const result = await session.run(`
        MATCH (u:User)
        RETURN count(u) > 0 AS hasUsers
      `);
      return result.records[0]?.get('hasUsers') || false;
    });
  }
}
