/**
 * PDF Generator — Format-Preserving Correction Strategy
 *
 * Instead of generating a PDF from scratch (which loses the original format),
 * this module:
 *   1. Copies ALL pages from the original PDF verbatim (preserving headers,
 *      footers, logos, fonts, layout — everything).
 *   2. Appends an "ANEXO DE CORRECCIONES" section using PDFKit that lists
 *      each correction with section reference, original text, and corrected text.
 *
 * This ensures the output has full legal validity because the original document
 * is embedded exactly as-is, and corrections are clearly documented.
 */

import { PDFDocument } from 'pdf-lib';
import PDFDocumentKit from 'pdfkit';
import { createLogger } from './logger';

const logger = createLogger();

// ── i18n labels for PDF generation ──────────────────────────────────────────
interface PdfLabels {
  annexTitle: string;
  annexSubtitle: string;
  program: string;
  date: string;
  corrections: string;
  modificationsProposed: string;
  note: string;
  correction: string;
  action: string;
  justification: string;
  evidence: string;
  suggestion: string;
  footerText: string;
  page: string;
  of: string;
  locale: string;
}

const PDF_LABELS: Record<string, PdfLabels> = {
  es: {
    annexTitle: 'ANEXO DE CORRECCIONES',
    annexSubtitle: 'Propuestas de Adecuación Curricular',
    program: 'Programa:',
    date: 'Fecha:',
    corrections: 'Correcciones:',
    modificationsProposed: 'modificaciones propuestas',
    note: 'NOTA: Las páginas anteriores corresponden al documento original del programa sin modificaciones. Las correcciones propuestas a continuación deben integrarse en las secciones indicadas para alcanzar la conformidad con los requisitos normativos.',
    correction: 'Corrección',
    action: 'Acción:',
    justification: 'Justificación:',
    evidence: 'Evidencia:',
    suggestion: 'Sugerencia:',
    footerText: 'Documento generado por el Sistema de Corrección Curricular.',
    page: 'Pág.',
    of: 'de',
    locale: 'es-AR',
  },
  gl: {
    annexTitle: 'ANEXO DE CORRECCIÓNS',
    annexSubtitle: 'Propostas de Adecuación Curricular',
    program: 'Programa:',
    date: 'Data:',
    corrections: 'Correccións:',
    modificationsProposed: 'modificacións propostas',
    note: 'NOTA: As páxinas anteriores corresponden ao documento orixinal do programa sen modificacións. As correccións propostas a continuación deben integrarse nas seccións indicadas para acadar a conformidade cos requisitos normativos.',
    correction: 'Corrección',
    action: 'Acción:',
    justification: 'Xustificación:',
    evidence: 'Evidencia:',
    suggestion: 'Suxestión:',
    footerText: 'Documento xerado polo Sistema de Corrección Curricular.',
    page: 'Páx.',
    of: 'de',
    locale: 'gl-ES',
  },
  pt: {
    annexTitle: 'ANEXO DE CORREÇÕES',
    annexSubtitle: 'Propostas de Adequação Curricular',
    program: 'Programa:',
    date: 'Data:',
    corrections: 'Correções:',
    modificationsProposed: 'modificações propostas',
    note: 'NOTA: As páginas anteriores correspondem ao documento original do programa sem modificações. As correções propostas a seguir devem ser integradas nas seções indicadas para alcançar a conformidade com os requisitos normativos.',
    correction: 'Correção',
    action: 'Ação:',
    justification: 'Justificação:',
    evidence: 'Evidência:',
    suggestion: 'Sugestão:',
    footerText: 'Documento gerado pelo Sistema de Correção Curricular.',
    page: 'Pág.',
    of: 'de',
    locale: 'pt-BR',
  },
  en: {
    annexTitle: 'CORRECTIONS ANNEX',
    annexSubtitle: 'Proposed Curricular Adjustments',
    program: 'Program:',
    date: 'Date:',
    corrections: 'Corrections:',
    modificationsProposed: 'proposed modifications',
    note: 'NOTE: The preceding pages correspond to the original program document without modifications. The corrections proposed below should be integrated into the indicated sections to achieve compliance with regulatory requirements.',
    correction: 'Correction',
    action: 'Action:',
    justification: 'Justification:',
    evidence: 'Evidence:',
    suggestion: 'Suggestion:',
    footerText: 'Document generated by the Curricular Correction System.',
    page: 'Page',
    of: 'of',
    locale: 'en-US',
  },
};

function getLabels(lang: string): PdfLabels {
  return PDF_LABELS[lang] || PDF_LABELS['es'];
}

/**
 * A single structured correction produced by the ProgramFixerAgent.
 */
export interface StructuredCorrection {
  /** Section or location in the original document */
  section: string;
  /** What type of change: 'agregar' | 'modificar' | 'enriquecer' */
  action: string;
  /** Brief description of why this correction is needed */
  justification: string;
  /** The corrected/added text to incorporate */
  correctedText: string;
  /** Priority: 'alta' | 'media' | 'baja' */
  priority: string;
  /** Optional: ID of the validated gap this correction addresses (for traceability) */
  gapId?: string;
  /** Optional: Status of the gap this correction addresses: 'partial' | 'missing' */
  status?: string;
  /** Optional: Evidence found in the program for this requirement (from comparison results) */
  evidence?: string;
  /** Optional: Suggestion for how to address this gap (from comparison results) */
  suggestion?: string;
}

/**
 * Parses the ProgramFixerAgent output (JSON array of corrections) into
 * structured objects. Handles markdown fences and partial/truncated JSON.
 */
export function parseCorrections(rawText: string): StructuredCorrection[] {
  // Strip markdown code fences
  let cleaned = rawText
    .replace(/^```(?:json)?\n?/m, '')
    .replace(/```\s*$/m, '')
    .trim();

  // Try full parse first
  try {
    const parsed = JSON.parse(cleaned);
    const items = parsed?.corrections ?? parsed;
    if (Array.isArray(items)) {
      const validItems = items.filter(isValidCorrection);
      const invalidCount = items.length - validItems.length;
      if (invalidCount > 0) {
        logger.warn('PDFGenerator', `Filtered out ${invalidCount} invalid corrections (missing section or correctedText)`);
      }
      const corrections = validItems.map(normalizeCorrection);
      const partialCount = corrections.filter(c => c.status === 'partial').length;
      const missingCount = corrections.filter(c => c.status === 'missing').length;
      const unknownCount = corrections.filter(c => !c.status).length;
      logger.info('PDFGenerator', `Successfully parsed ${corrections.length} corrections from structured JSON: ${partialCount} partial, ${missingCount} missing, ${unknownCount} unknown status`);
      return corrections;
    }
  } catch (err) {
    logger.warn('PDFGenerator', 'Failed to parse as complete JSON, falling back to object extraction', err as Error);
  }

  // Fallback: extract complete JSON objects from the text
  const objects: any[] = [];
  let depth = 0;
  let start = -1;

  for (let i = 0; i < cleaned.length; i++) {
    const ch = cleaned[i];
    if (ch === '{') {
      if (depth === 0) start = i;
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0 && start >= 0) {
        try {
          const obj = JSON.parse(cleaned.substring(start, i + 1));
          objects.push(obj);
        } catch { /* skip malformed */ }
        start = -1;
      }
    }
  }

  const validObjects = objects.filter(isValidCorrection);
  const invalidCount = objects.length - validObjects.length;
  if (invalidCount > 0) {
    logger.warn('PDFGenerator', `Filtered out ${invalidCount} invalid corrections from fallback extraction`);
  }
  const corrections = validObjects.map(normalizeCorrection);
  const partialCount = corrections.filter(c => c.status === 'partial').length;
  const missingCount = corrections.filter(c => c.status === 'missing').length;
  const unknownCount = corrections.filter(c => !c.status).length;
  logger.info('PDFGenerator', `Extracted ${corrections.length} corrections using fallback: ${partialCount} partial, ${missingCount} missing, ${unknownCount} unknown status`);
  
  return corrections;
}

function isValidCorrection(obj: any): boolean {
  return obj && typeof obj.section === 'string' && (typeof obj.correctedText === 'string' || typeof obj.corrected_text === 'string' || typeof obj.texto_corregido === 'string');
}

function normalizeCorrection(obj: any): StructuredCorrection {
  return {
    section: String(obj.section ?? obj.seccion ?? ''),
    action: String(obj.action ?? obj.accion ?? 'modificar'),
    justification: String(obj.justification ?? obj.justificacion ?? obj.reason ?? ''),
    correctedText: String(obj.correctedText ?? obj.corrected_text ?? obj.texto_corregido ?? ''),
    priority: String(obj.priority ?? obj.prioridad ?? 'media'),
    gapId: obj.gapId ?? obj.gap_id ?? undefined,
    status: obj.status ?? undefined,
  };
}

/**
 * Generates a corrected PDF by copying the original PDF pages verbatim
 * and appending a structured "ANEXO DE CORRECCIONES" section.
 *
 * @param programName    Display name for the program
 * @param originalPdf    Buffer of the original PDF (uploaded by user)
 * @param corrections    Structured corrections from ProgramFixerAgent
 * @param correctedText  Raw text from the agent (for reference)
 * @param lang           Language code for PDF labels (es, gl, pt, en)
 * @returns              Buffer of the combined PDF
 */
export async function generateCorrectedProgramPDF(
  programName: string,
  originalPdf: Buffer | null,
  corrections: StructuredCorrection[],
  correctedText: string,
  lang: string = 'es'
): Promise<Buffer> {
  logger.info('PDFGenerator', `Generating format-preserving corrected PDF for: ${programName} (lang: ${lang})`);
  logger.info('PDFGenerator', `Received ${corrections.length} corrections to include in PDF annex`);

  const labels = getLabels(lang);

  // ── Step 1: Create the appendix pages with PDFKit ────────────────────
  const appendixBuffer = await generateAppendixPDF(programName, corrections, correctedText, labels);

  if (!originalPdf || originalPdf.length === 0) {
    logger.warn('PDFGenerator', 'No original PDF available — returning appendix-only PDF');
    return appendixBuffer;
  }

  // ── Step 2: Merge original + appendix using pdf-lib ──────────────────
  try {
    const mergedPdf = await PDFDocument.create();

    // Copy all pages from the original PDF
    const originalDoc = await PDFDocument.load(originalPdf, { ignoreEncryption: true });
    const originalPages = await mergedPdf.copyPages(originalDoc, originalDoc.getPageIndices());
    for (const page of originalPages) {
      mergedPdf.addPage(page);
    }

    logger.info('PDFGenerator', `Copied ${originalPages.length} pages from original PDF`);

    // Copy all pages from the appendix PDF
    const appendixDoc = await PDFDocument.load(appendixBuffer);
    const appendixPages = await mergedPdf.copyPages(appendixDoc, appendixDoc.getPageIndices());
    for (const page of appendixPages) {
      mergedPdf.addPage(page);
    }

    logger.info('PDFGenerator', `Added ${appendixPages.length} appendix pages`);

    // Set metadata
    mergedPdf.setTitle(`${programName} — Programa Corregido`);
    mergedPdf.setSubject('Documento corregido bajo conformidad normativa');
    mergedPdf.setCreator('PDF Knowledge Graph — Sistema de Corrección Curricular');
    mergedPdf.setProducer('pdf-lib + PDFKit');
    mergedPdf.setCreationDate(new Date());

    const mergedBytes = await mergedPdf.save();
    return Buffer.from(mergedBytes);
  } catch (mergeError: any) {
    logger.error('PDFGenerator', 'Error merging PDFs, returning appendix only', mergeError);
    return appendixBuffer;
  }
}

/**
 * Generates the appendix PDF with structured corrections using PDFKit.
 */
async function generateAppendixPDF(
  programName: string,
  corrections: StructuredCorrection[],
  correctedText: string,
  labels: PdfLabels
): Promise<Buffer> {
  logger.info('PDFGenerator', `Generating appendix PDF with ${corrections.length} corrections`);
  
  return new Promise((resolve, reject) => {
    try {
      const chunks: Buffer[] = [];

      // Reserve bottom margin so footer never overlaps body text
      const BOTTOM_MARGIN = 60;

      const doc = new PDFDocumentKit({
        size: 'A4',
        margins: { top: 54, bottom: BOTTOM_MARGIN, left: 54, right: 54 },
        bufferPages: true,
      });

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      const margin = 54;
      const pageWidth = doc.page.width;
      const pageHeight = doc.page.height;
      const writeWidth = pageWidth - margin * 2;

      /** Available vertical space on the current page before the footer zone */
      const availableY = () => pageHeight - BOTTOM_MARGIN - margin;

      /** Ensures at least `needed` pts are available; adds a page if not. */
      const ensureSpace = (needed: number) => {
        if (doc.y + needed > availableY()) {
          doc.addPage();
        }
      };

      const title = programName.replace(/\.pdf$/i, '').replace(/_/g, ' ');

      // ── Cover page for the appendix ──────────────────────────────────────
      // Decorative top bar
      doc.rect(0, 0, pageWidth, 8).fill('#1e40af');

      doc.moveDown(4);

      doc.fillColor('#1e293b')
         .font('Helvetica-Bold')
         .fontSize(22)
         .text(labels.annexTitle, { align: 'center' });

      doc.moveDown(0.8);

      doc.fillColor('#475569')
         .font('Helvetica')
         .fontSize(12)
         .text(labels.annexSubtitle, { align: 'center' });

      doc.moveDown(2);

      // Info box — measure each line individually then set Y below the box
      const boxY = doc.y;
      const BOX_LINE_H = 18;
      const BOX_PAD_V = 12;
      const infoBoxHeight = BOX_LINE_H * 3 + BOX_PAD_V * 2;

      doc.rect(margin, boxY, writeWidth, infoBoxHeight)
         .lineWidth(1)
         .strokeColor('#cbd5e1')
         .fillAndStroke('#f8fafc', '#cbd5e1');

      doc.fillColor('#334155')
         .font('Helvetica-Bold')
         .fontSize(10)
         .text(labels.program, margin + 15, boxY + BOX_PAD_V, { continued: true })
         .font('Helvetica')
         .text(`  ${title}`);

      doc.fillColor('#334155')
         .font('Helvetica-Bold')
         .fontSize(10)
         .text(labels.date, margin + 15, boxY + BOX_PAD_V + BOX_LINE_H, { continued: true })
         .font('Helvetica')
         .text(`  ${new Date().toLocaleDateString(labels.locale, { year: 'numeric', month: 'long', day: 'numeric' })}`);

      doc.fillColor('#334155')
         .font('Helvetica-Bold')
         .fontSize(10)
         .text(labels.corrections, margin + 15, boxY + BOX_PAD_V + BOX_LINE_H * 2, { continued: true })
         .font('Helvetica')
         .text(`  ${corrections.length} ${labels.modificationsProposed}`);

      // Advance Y cursor to below the info box
      doc.y = boxY + infoBoxHeight + 10;

      doc.moveDown(0.8);

      doc.fillColor('#64748b')
         .font('Helvetica')
         .fontSize(9)
         .text(labels.note, { align: 'justify', width: writeWidth });

      doc.moveDown(1.5);

      // Divider line
      doc.strokeColor('#e2e8f0')
         .lineWidth(1)
         .moveTo(margin, doc.y)
         .lineTo(pageWidth - margin, doc.y)
         .stroke();

      doc.moveDown(1);

      // ── Render each correction ─────────────────────────────────────────
      if (corrections.length > 0) {
        for (let idx = 0; idx < corrections.length; idx++) {
          const c = corrections[idx];

          // Pre-measure heights for this block so we can decide upfront
          // whether to add a page rather than splitting mid-block.
          const justH = c.justification
            ? doc.heightOfString(c.justification, { width: writeWidth - 12 }) + 8
            : 0;
          const textH = doc.heightOfString(c.correctedText, { width: writeWidth - 30 });
          const boxH = textH + 16;
          // Minimum block: header (22) + action line (20) + justification + text box + separator (12)
          const totalBlockH = 22 + 20 + justH + boxH + 20;

          // Add page if the full block won't fit; 80 is a soft minimum header-only threshold
          ensureSpace(Math.min(totalBlockH, 80));

          // Priority color badge
          const priorityColors: Record<string, string> = {
            alta: '#dc2626',
            high: '#dc2626',
            media: '#f59e0b',
            medium: '#f59e0b',
            baja: '#22c55e',
            low: '#22c55e',
          };
          const pColor = priorityColors[c.priority.toLowerCase()] || '#6b7280';

          // Correction number + section header
          const headerY = doc.y;
          doc.rect(margin, headerY, 4, 16).fill('#1e40af');

          doc.fillColor('#1e293b')
             .font('Helvetica-Bold')
             .fontSize(11)
             .text(`${labels.correction} ${idx + 1}: ${c.section}`, margin + 12, headerY + 2, { width: writeWidth - 100 });

          // Priority badge
          const badgeText = c.priority.toUpperCase();
          const badgeWidth = doc.widthOfString(badgeText) + 12;
          doc.roundedRect(pageWidth - margin - badgeWidth - 5, headerY, badgeWidth, 16, 3).fill(pColor);
          doc.fillColor('#ffffff')
             .font('Helvetica-Bold')
             .fontSize(8)
             .text(badgeText, pageWidth - margin - badgeWidth, headerY + 4, { width: badgeWidth, align: 'center' });

          doc.y = headerY + 22;

          // Action type
          doc.fillColor('#6b7280')
             .font('Helvetica-Bold')
             .fontSize(9)
             .text(labels.action + ' ', margin + 12, doc.y, { continued: true })
             .font('Helvetica')
             .fillColor('#475569')
             .text(c.action);

          doc.moveDown(0.4);

          // Evidence (from comparison results — matches HTML output)
          if (c.evidence) {
            doc.fillColor('#6b7280')
               .font('Helvetica-Bold')
               .fontSize(9)
               .text(labels.evidence + ' ', margin + 12, doc.y, { continued: true })
               .font('Helvetica')
               .fillColor('#475569')
               .text(c.evidence, { width: writeWidth - 12 });

            doc.moveDown(0.4);
          }

          // Suggestion (from comparison results — matches HTML output)
          if (c.suggestion && c.suggestion !== 'Ninguna') {
            doc.fillColor('#6b7280')
               .font('Helvetica-Bold')
               .fontSize(9)
               .text(labels.suggestion + ' ', margin + 12, doc.y, { continued: true })
               .font('Helvetica')
               .fillColor('#475569')
               .text(c.suggestion, { width: writeWidth - 12 });

            doc.moveDown(0.4);
          }

          // Justification
          if (c.justification) {
            doc.fillColor('#6b7280')
               .font('Helvetica-Bold')
               .fontSize(9)
               .text(labels.justification + ' ', margin + 12, doc.y, { continued: true })
               .font('Helvetica')
               .fillColor('#475569')
               .text(c.justification, { width: writeWidth - 12 });

            doc.moveDown(0.4);
          }

          // Corrected text box — ensure it fits on this page
          ensureSpace(boxH + 20);

          const finalBoxY = doc.y;
          doc.rect(margin + 8, finalBoxY, writeWidth - 8, boxH)
             .lineWidth(0.5)
             .fillAndStroke('#f0fdf4', '#bbf7d0');

          doc.fillColor('#166534')
             .font('Helvetica')
             .fontSize(9)
             .text(c.correctedText, margin + 20, finalBoxY + 8, {
               width: writeWidth - 30,
               align: 'justify',
               lineGap: 2,
             });

          doc.y = finalBoxY + boxH + 12;

          // Separator between corrections
          if (idx < corrections.length - 1) {
            doc.strokeColor('#e2e8f0')
               .lineWidth(0.5)
               .moveTo(margin + 20, doc.y)
               .lineTo(pageWidth - margin - 20, doc.y)
               .stroke();
            doc.moveDown(0.8);
          }
        }
        logger.info('PDFGenerator', `Successfully rendered all ${corrections.length} corrections in PDF`);
      } else {
        // No structured corrections — render the raw corrected text
        doc.fillColor('#475569')
           .font('Helvetica')
           .fontSize(10);

        const lines = correctedText.split('\n');
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed) continue;

          // Basic markdown-like rendering for fallback
          if (trimmed.startsWith('# ')) {
            ensureSpace(30);
            doc.moveDown(0.8);
            const currentY = doc.y;
            doc.rect(margin, currentY, 4, 16).fill('#1e40af');
            doc.fillColor('#1e293b')
               .font('Helvetica-Bold')
               .fontSize(12)
               .text(trimmed.substring(2), margin + 12, currentY + 1, { width: writeWidth - 12 });
            doc.moveDown(0.6);
          } else if (trimmed.startsWith('## ')) {
            ensureSpace(24);
            doc.moveDown(0.4);
            doc.fillColor('#334155')
               .font('Helvetica-Bold')
               .fontSize(10)
               .text(trimmed.substring(3), { width: writeWidth });
            doc.moveDown(0.4);
          } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
            const lh = doc.heightOfString('•  ' + trimmed.substring(2), { width: writeWidth - 15 });
            ensureSpace(lh + 6);
            doc.fillColor('#475569')
               .font('Helvetica')
               .fontSize(9)
               .text('•  ' + trimmed.substring(2), margin + 15, doc.y, {
                 width: writeWidth - 15,
                 align: 'justify',
                 lineGap: 2,
               });
            doc.moveDown(0.3);
          } else {
            const lh = doc.heightOfString(trimmed, { width: writeWidth });
            ensureSpace(lh + 6);
            doc.fillColor('#475569')
               .font('Helvetica')
               .fontSize(9)
               .text(trimmed, {
                 width: writeWidth,
                 align: 'justify',
                 lineGap: 2,
               });
            doc.moveDown(0.4);
          }
        }
      }

      // ── Headers and Footers ──────────────────────────────────────────────
      const pages = doc.bufferedPageRange();
      for (let j = 0; j < pages.count; j++) {
        doc.switchToPage(j);

        // Temporarily remove bottom margin so we can draw in the footer zone
        const savedBottom = doc.page.margins.bottom;
        doc.page.margins.bottom = 0;

        // Header (skip cover page)
        if (j > 0) {
          doc.fontSize(8)
             .fillColor('#94a3b8')
             .font('Helvetica')
             .text(`${labels.annexTitle} — ${title.toUpperCase()}`, margin, 30, { align: 'left' });

          doc.strokeColor('#e2e8f0')
             .lineWidth(0.5)
             .moveTo(margin, 42)
             .lineTo(pageWidth - margin, 42)
             .stroke();
        }

        // Footer
        doc.strokeColor('#e2e8f0')
           .lineWidth(0.5)
           .moveTo(margin, pageHeight - 45)
           .lineTo(pageWidth - margin, pageHeight - 45)
           .stroke();

        doc.fontSize(8)
           .fillColor('#94a3b8')
           .font('Helvetica');

        doc.text(labels.footerText, margin, pageHeight - 36, { align: 'left' });
        doc.text(`${labels.page} ${j + 1} ${labels.of} ${pages.count}`, pageWidth - margin - 80, pageHeight - 36, { width: 80, align: 'right' });

        doc.page.margins.bottom = savedBottom;
      }

      doc.end();
    } catch (error) {
      logger.error('PDFGenerator', 'Error generating appendix PDF', error as Error);
      reject(error);
    }
  });
}
