/**
 * PDF Generator — Format-Preserving Correction Strategy
 *
 * Instead of generating a PDF from scratch (which loses the original format),
 * this module:
 *   1. Copies ALL pages from the original PDF verbatim (preserving headers,
 *      footers, logos, fonts, layout — everything).
 *   2. Appends an "ANEXO DE CORRECCIONES" section using PDFKit that lists
 *      each correction with section reference, original text, and corrected text.
 *
 * This ensures the output has full legal validity because the original document
 * is embedded exactly as-is, and corrections are clearly documented.
 */

import { PDFDocument } from 'pdf-lib';
import PDFDocumentKit from 'pdfkit';
import { createLogger } from './logger';

const logger = createLogger();

// ── i18n labels for PDF generation ──────────────────────────────────────────
interface PdfLabels {
  annexTitle: string;
  annexSubtitle: string;
  program: string;
  date: string;
  corrections: string;
  modificationsProposed: string;
  note: string;
  correction: string;
  action: string;
  justification: string;
  footerText: string;
  page: string;
  of: string;
  locale: string;
}

const PDF_LABELS: Record<string, PdfLabels> = {
  es: {
    annexTitle: 'ANEXO DE CORRECCIONES',
    annexSubtitle: 'Propuestas de Adecuación Curricular',
    program: 'Programa:',
    date: 'Fecha:',
    corrections: 'Correcciones:',
    modificationsProposed: 'modificaciones propuestas',
    note: 'NOTA: Las páginas anteriores corresponden al documento original del programa sin modificaciones. Las correcciones propuestas a continuación deben integrarse en las secciones indicadas para alcanzar la conformidad con los requisitos normativos.',
    correction: 'Corrección',
    action: 'Acción:',
    justification: 'Justificación:',
    footerText: 'Documento generado por el Sistema de Corrección Curricular.',
    page: 'Pág.',
    of: 'de',
    locale: 'es-AR',
  },
  gl: {
    annexTitle: 'ANEXO DE CORRECCIÓNS',
    annexSubtitle: 'Propostas de Adecuación Curricular',
    program: 'Programa:',
    date: 'Data:',
    corrections: 'Correccións:',
    modificationsProposed: 'modificacións propostas',
    note: 'NOTA: As páxinas anteriores corresponden ao documento orixinal do programa sen modificacións. As correccións propostas a continuación deben integrarse nas seccións indicadas para acadar a conformidade cos requisitos normativos.',
    correction: 'Corrección',
    action: 'Acción:',
    justification: 'Xustificación:',
    footerText: 'Documento xerado polo Sistema de Corrección Curricular.',
    page: 'Páx.',
    of: 'de',
    locale: 'gl-ES',
  },
  pt: {
    annexTitle: 'ANEXO DE CORREÇÕES',
    annexSubtitle: 'Propostas de Adequação Curricular',
    program: 'Programa:',
    date: 'Data:',
    corrections: 'Correções:',
    modificationsProposed: 'modificações propostas',
    note: 'NOTA: As páginas anteriores correspondem ao documento original do programa sem modificações. As correções propostas a seguir devem ser integradas nas seções indicadas para alcançar a conformidade com os requisitos normativos.',
    correction: 'Correção',
    action: 'Ação:',
    justification: 'Justificação:',
    footerText: 'Documento gerado pelo Sistema de Correção Curricular.',
    page: 'Pág.',
    of: 'de',
    locale: 'pt-BR',
  },
  en: {
    annexTitle: 'CORRECTIONS ANNEX',
    annexSubtitle: 'Proposed Curricular Adjustments',
    program: 'Program:',
    date: 'Date:',
    corrections: 'Corrections:',
    modificationsProposed: 'proposed modifications',
    note: 'NOTE: The preceding pages correspond to the original program document without modifications. The corrections proposed below should be integrated into the indicated sections to achieve compliance with regulatory requirements.',
    correction: 'Correction',
    action: 'Action:',
    justification: 'Justification:',
    footerText: 'Document generated by the Curricular Correction System.',
    page: 'Page',
    of: 'of',
    locale: 'en-US',
  },
};

function getLabels(lang: string): PdfLabels {
  return PDF_LABELS[lang] || PDF_LABELS['es'];
}

/**
 * A single structured correction produced by the ProgramFixerAgent.
 */
export interface StructuredCorrection {
  /** Section or location in the original document */
  section: string;
  /** What type of change: 'agregar' | 'modificar' | 'enriquecer' */
  action: string;
  /** Brief description of why this correction is needed */
  justification: string;
  /** The corrected/added text to incorporate */
  correctedText: string;
  /** Priority: 'alta' | 'media' | 'baja' */
  priority: string;
}

/**
 * Parses the ProgramFixerAgent output (JSON array of corrections) into
 * structured objects. Handles markdown fences and partial/truncated JSON.
 */
export function parseCorrections(rawText: string): StructuredCorrection[] {
  // Strip markdown code fences
  let cleaned = rawText
    .replace(/^```(?:json)?\n?/m, '')
    .replace(/```\s*$/m, '')
    .trim();

  // Try full parse first
  try {
    const parsed = JSON.parse(cleaned);
    const items = parsed?.corrections ?? parsed;
    if (Array.isArray(items)) {
      return items.filter(isValidCorrection).map(normalizeCorrection);
    }
  } catch { /* fall through */ }

  // Fallback: extract complete JSON objects from the text
  const objects: any[] = [];
  let depth = 0;
  let start = -1;

  for (let i = 0; i < cleaned.length; i++) {
    const ch = cleaned[i];
    if (ch === '{') {
      if (depth === 0) start = i;
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0 && start >= 0) {
        try {
          const obj = JSON.parse(cleaned.substring(start, i + 1));
          objects.push(obj);
        } catch { /* skip malformed */ }
        start = -1;
      }
    }
  }

  return objects.filter(isValidCorrection).map(normalizeCorrection);
}

function isValidCorrection(obj: any): boolean {
  return obj && typeof obj.section === 'string' && (typeof obj.correctedText === 'string' || typeof obj.corrected_text === 'string' || typeof obj.texto_corregido === 'string');
}

function normalizeCorrection(obj: any): StructuredCorrection {
  return {
    section: String(obj.section ?? obj.seccion ?? ''),
    action: String(obj.action ?? obj.accion ?? 'modificar'),
    justification: String(obj.justification ?? obj.justificacion ?? obj.reason ?? ''),
    correctedText: String(obj.correctedText ?? obj.corrected_text ?? obj.texto_corregido ?? ''),
    priority: String(obj.priority ?? obj.prioridad ?? 'media'),
  };
}

/**
 * Generates a corrected PDF by copying the original PDF pages verbatim
 * and appending a structured "ANEXO DE CORRECCIONES" section.
 *
 * @param programName    Display name for the program
 * @param originalPdf    Buffer of the original PDF (uploaded by user)
 * @param corrections    Structured corrections from ProgramFixerAgent
 * @param correctedText  Raw text from the agent (for reference)
 * @param lang           Language code for PDF labels (es, gl, pt, en)
 * @returns              Buffer of the combined PDF
 */
export async function generateCorrectedProgramPDF(
  programName: string,
  originalPdf: Buffer | null,
  corrections: StructuredCorrection[],
  correctedText: string,
  lang: string = 'es'
): Promise<Buffer> {
  logger.info('PDFGenerator', `Generating format-preserving corrected PDF for: ${programName} (lang: ${lang})`);

  const labels = getLabels(lang);

  // ── Step 1: Create the appendix pages with PDFKit ────────────────────
  const appendixBuffer = await generateAppendixPDF(programName, corrections, correctedText, labels);

  if (!originalPdf || originalPdf.length === 0) {
    logger.warn('PDFGenerator', 'No original PDF available — returning appendix-only PDF');
    return appendixBuffer;
  }

  // ── Step 2: Merge original + appendix using pdf-lib ──────────────────
  try {
    const mergedPdf = await PDFDocument.create();

    // Copy all pages from the original PDF
    const originalDoc = await PDFDocument.load(originalPdf, { ignoreEncryption: true });
    const originalPages = await mergedPdf.copyPages(originalDoc, originalDoc.getPageIndices());
    for (const page of originalPages) {
      mergedPdf.addPage(page);
    }

    logger.info('PDFGenerator', `Copied ${originalPages.length} pages from original PDF`);

    // Copy all pages from the appendix PDF
    const appendixDoc = await PDFDocument.load(appendixBuffer);
    const appendixPages = await mergedPdf.copyPages(appendixDoc, appendixDoc.getPageIndices());
    for (const page of appendixPages) {
      mergedPdf.addPage(page);
    }

    logger.info('PDFGenerator', `Added ${appendixPages.length} appendix pages`);

    // Set metadata
    mergedPdf.setTitle(`${programName} — Programa Corregido`);
    mergedPdf.setSubject('Documento corregido bajo conformidad normativa');
    mergedPdf.setCreator('PDF Knowledge Graph — Sistema de Corrección Curricular');
    mergedPdf.setProducer('pdf-lib + PDFKit');
    mergedPdf.setCreationDate(new Date());

    const mergedBytes = await mergedPdf.save();
    return Buffer.from(mergedBytes);
  } catch (mergeError: any) {
    logger.error('PDFGenerator', 'Error merging PDFs, returning appendix only', mergeError);
    return appendixBuffer;
  }
}

/**
 * Generates the appendix PDF with structured corrections using PDFKit.
 */
async function generateAppendixPDF(
  programName: string,
  corrections: StructuredCorrection[],
  correctedText: string,
  labels: PdfLabels
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const chunks: Buffer[] = [];
      const doc = new PDFDocumentKit({
        size: 'A4',
        margin: 54,
        bufferPages: true
      });

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      const margin = 54;
      const pageWidth = doc.page.width;
      const pageHeight = doc.page.height;
      const writeWidth = pageWidth - margin * 2;

      const title = programName.replace(/\.pdf$/i, '').replace(/_/g, ' ');

      // ── Separator / Cover page for the appendix ──────────────────────
      // Decorative top bar
      doc.rect(0, 0, pageWidth, 8).fill('#1e40af');

      doc.moveDown(4);

      // Title block
      doc.fillColor('#1e293b')
         .font('Helvetica-Bold')
         .fontSize(22)
         .text(labels.annexTitle, { align: 'center' });

      doc.moveDown(0.8);

      doc.fillColor('#475569')
         .font('Helvetica')
         .fontSize(12)
         .text(labels.annexSubtitle, { align: 'center' });

      doc.moveDown(2);

      // Info box
      const boxY = doc.y;
      doc.rect(margin, boxY, writeWidth, 80)
         .lineWidth(1)
         .strokeColor('#cbd5e1')
         .fillAndStroke('#f8fafc', '#cbd5e1');

      doc.fillColor('#334155')
         .font('Helvetica-Bold')
         .fontSize(10)
         .text(labels.program, margin + 15, boxY + 12, { continued: true })
         .font('Helvetica')
         .text(`  ${title}`);

      doc.fillColor('#334155')
         .font('Helvetica-Bold')
         .fontSize(10)
         .text(labels.date, margin + 15, boxY + 30, { continued: true })
         .font('Helvetica')
         .text(`  ${new Date().toLocaleDateString(labels.locale, { year: 'numeric', month: 'long', day: 'numeric' })}`);

      doc.fillColor('#334155')
         .font('Helvetica-Bold')
         .fontSize(10)
         .text(labels.corrections, margin + 15, boxY + 48, { continued: true })
         .font('Helvetica')
         .text(`  ${corrections.length} ${labels.modificationsProposed}`);

      doc.y = boxY + 95;

      doc.moveDown(1);

      doc.fillColor('#64748b')
         .font('Helvetica')
         .fontSize(9)
         .text(
           labels.note,
           { align: 'justify', width: writeWidth }
         );

      doc.moveDown(2);

      // Divider line
      doc.strokeColor('#e2e8f0')
         .lineWidth(1)
         .moveTo(margin, doc.y)
         .lineTo(pageWidth - margin, doc.y)
         .stroke();

      doc.moveDown(1);

      // ── Render each correction ───────────────────────────────────────
      if (corrections.length > 0) {
        for (let idx = 0; idx < corrections.length; idx++) {
          const c = corrections[idx];

          // Check if we need a new page (leave room for at least the header)
          if (doc.y > pageHeight - 150) {
            doc.addPage();
          }

          // Priority color badge
          const priorityColors: Record<string, string> = {
            alta: '#dc2626',
            media: '#f59e0b',
            baja: '#22c55e',
          };
          const pColor = priorityColors[c.priority.toLowerCase()] || '#6b7280';

          // Correction number + section header
          const headerY = doc.y;
          doc.rect(margin, headerY, 4, 16).fill('#1e40af');

          doc.fillColor('#1e293b')
             .font('Helvetica-Bold')
             .fontSize(11)
             .text(`${labels.correction} ${idx + 1}: ${c.section}`, margin + 12, headerY + 2, { width: writeWidth - 100 });

          // Priority badge
          const badgeText = c.priority.toUpperCase();
          const badgeWidth = doc.widthOfString(badgeText) + 12;
          doc.roundedRect(pageWidth - margin - badgeWidth - 5, headerY, badgeWidth, 16, 3)
             .fill(pColor);
          doc.fillColor('#ffffff')
             .font('Helvetica-Bold')
             .fontSize(8)
             .text(badgeText, pageWidth - margin - badgeWidth, headerY + 4, { width: badgeWidth, align: 'center' });

          doc.y = headerY + 22;

          // Action type
          doc.fillColor('#6b7280')
             .font('Helvetica-Bold')
             .fontSize(9)
             .text(labels.action + ' ', margin + 12, doc.y, { continued: true })
             .font('Helvetica')
             .fillColor('#475569')
             .text(c.action);

          doc.moveDown(0.3);

          // Justification
          if (c.justification) {
            doc.fillColor('#6b7280')
               .font('Helvetica-Bold')
               .fontSize(9)
               .text(labels.justification + ' ', margin + 12, doc.y, { continued: true })
               .font('Helvetica')
               .fillColor('#475569')
               .text(c.justification, { width: writeWidth - 12 });

            doc.moveDown(0.3);
          }

          // Corrected text box
          const textBoxY = doc.y;
          const textHeight = doc.heightOfString(c.correctedText, { width: writeWidth - 30 });
          const boxHeight = textHeight + 16;

          // Check page overflow for the text box
          if (textBoxY + boxHeight > pageHeight - 60) {
            doc.addPage();
          }

          const finalBoxY = doc.y;
          doc.rect(margin + 8, finalBoxY, writeWidth - 8, boxHeight)
             .lineWidth(0.5)
             .fillAndStroke('#f0fdf4', '#bbf7d0');

          doc.fillColor('#166534')
             .font('Helvetica')
             .fontSize(9)
             .text(c.correctedText, margin + 20, finalBoxY + 8, {
               width: writeWidth - 30,
               align: 'justify',
               lineGap: 2
             });

          doc.y = finalBoxY + boxHeight + 12;

          // Separator between corrections
          if (idx < corrections.length - 1) {
            doc.strokeColor('#e2e8f0')
               .lineWidth(0.5)
               .moveTo(margin + 20, doc.y)
               .lineTo(pageWidth - margin - 20, doc.y)
               .stroke();
            doc.moveDown(0.8);
          }
        }
      } else {
        // No structured corrections — render the raw corrected text
        doc.fillColor('#475569')
           .font('Helvetica')
           .fontSize(10);

        const lines = correctedText.split('\n');
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed) continue;

          if (doc.y > pageHeight - 80) {
            doc.addPage();
          }

          // Basic markdown-like rendering for fallback
          if (trimmed.startsWith('# ')) {
            doc.moveDown(0.8);
            const currentY = doc.y;
            doc.rect(margin, currentY, 4, 16).fill('#1e40af');
            doc.fillColor('#1e293b')
               .font('Helvetica-Bold')
               .fontSize(12)
               .text(trimmed.substring(2), margin + 12, currentY + 1, { width: writeWidth - 12 });
            doc.moveDown(0.6);
          } else if (trimmed.startsWith('## ')) {
            doc.moveDown(0.4);
            doc.fillColor('#334155')
               .font('Helvetica-Bold')
               .fontSize(10)
               .text(trimmed.substring(3), { width: writeWidth });
            doc.moveDown(0.4);
          } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
            doc.fillColor('#475569')
               .font('Helvetica')
               .fontSize(9)
               .text('•  ' + trimmed.substring(2), margin + 15, doc.y, {
                 width: writeWidth - 15,
                 align: 'justify',
                 lineGap: 2
               });
            doc.moveDown(0.3);
          } else {
            doc.fillColor('#475569')
               .font('Helvetica')
               .fontSize(9)
               .text(trimmed, {
                 width: writeWidth,
                 align: 'justify',
                 lineGap: 2
               });
            doc.moveDown(0.4);
          }
        }
      }

      // ── Headers and Footers ──────────────────────────────────────────
      const pages = doc.bufferedPageRange();
      for (let j = 0; j < pages.count; j++) {
        doc.switchToPage(j);

        const oldBottom = doc.page.margins.bottom;
        doc.page.margins.bottom = 0;

        // Header
        if (j > 0) {
          doc.fontSize(8)
             .fillColor('#94a3b8')
             .font('Helvetica')
             .text(`${labels.annexTitle} — ${title.toUpperCase()}`, margin, 30, { align: 'left' });

          doc.strokeColor('#e2e8f0')
             .lineWidth(0.5)
             .moveTo(margin, 42)
             .lineTo(pageWidth - margin, 42)
             .stroke();
        }

        // Footer
        doc.strokeColor('#e2e8f0')
           .lineWidth(0.5)
           .moveTo(margin, pageHeight - 45)
           .lineTo(pageWidth - margin, pageHeight - 45)
           .stroke();

        doc.fontSize(8)
           .fillColor('#94a3b8')
           .font('Helvetica')
           .text(labels.footerText, margin, pageHeight - 36, { align: 'left', continued: true })
           .text(`${labels.page} ${j + 1} ${labels.of} ${pages.count}`, pageWidth - margin - 80, pageHeight - 36, { width: 80, align: 'right' });

        doc.page.margins.bottom = oldBottom;
      }

      doc.end();
    } catch (error) {
      logger.error('PDFGenerator', 'Error generating appendix PDF', error as Error);
      reject(error);
    }
  });
}
